name: cron

on:
  schedule:
    - cron: "0 16 * * *"

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: npm ci --no-optional

      - name: Update Dependencies
        run: |
          rm -rf package-lock.json node_modules
          npx npm-check-updates -u
          npm install
          npm audit fix
          git add -u :/
          git commit -m "update dependencies"

      - name: Unit Test
        run: npm test

      - name: Lint Code
        run: npm run lint

      - name: Check Formatting
        run: npm run check

      - name: Build Package
        run: npm run build

      - name: Tag Release
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          npm version patch
          VERSION=v`cat package.json | jq -r .version`
          git push
          git push origin $VERSION

      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Storybook
        run: npm run build:storybook

      - name: Deploy Storybook
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
