name: NPM Check Updates
on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npx npm-check-updates --upgrade --doctor --target major
    - run: npx npm-check-updates --upgrade --doctor --target minor
    - run: npx npm-check-updates --upgrade --doctor --target patch
#     - uses: EndBug/add-and-commit@v7
