name: pr

on:
  pull_request:
    branches: [master]

jobs:
  pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: npm ci --no-optional

      - name: Unit Test
        run: npm run test:ci

      - name: Lint Code
        run: npm run lint

      - name: Check Formatting
        run: npm run check

      - name: Build Package
        run: npm run build

      - name: Build Storybook
        run: npm run build:storybook
